---
title: "TeamWeR - Predicting Diamond Price"
subtitle: "Datasci 203 Lab 2"
author: "Ivy Chan, Jonathan Hodges, Dipika Kumar, Christian Lee"
output:
  pdf_document
header-includes:
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages and set options, include=FALSE}
library(tidyverse)
library(magrittr)
library(stargazer)
library(sandwich)
library(lmtest)
library(ggplot2)
library(reshape2)
library(dplyr)
library(tidyr)
library(moments)
library(olsrr)
library(caret)
library(mltools)
library(data.table)

theme_set(theme_bw())
```

```{r load data, message = FALSE, include=FALSE}
original_diamonds <- read.csv("./data/diamonds.csv")
```

```{r split data for exploration set and confirmation set}
#use 70% of dataset as confirmation_set and 30% as exploration_set
sample <- sample(c(TRUE, FALSE), nrow(diamonds), replace=TRUE, prob=c(0.7,0.3))
confirmation_set <- original_diamonds[sample, ]
diamonds <- original_diamonds[!sample, ]
nrow(confirmation_set)
nrow(diamonds)
```

```{r summary dataset, include=FALSE}
head(diamonds)
summary(diamonds)
dim(diamonds)
summary(factor(diamonds$cut))
summary(factor(diamonds$carat))
summary(factor(diamonds$color))
summary(factor(diamonds$clarity))
summary(factor(diamonds$depth))
summary(factor(diamonds$table))
summary(factor(diamonds$price))
summary(factor(diamonds$x))
summary(factor(diamonds$y))
summary(factor(diamonds$z))
```

```{r data cleaning, message = FALSE, include=FALSE}
diamonds %>% drop_na()
diamonds <- subset(diamonds, select=c(carat, cut, color, clarity, depth, table, price, x, y, z))
```

```{r checking dataset}
summary(diamonds)
dim(diamonds)
boxplot(price ~ x, data=diamonds, main="Diamonds",
   xlab="Length", ylab="Price")

boxplot(price ~ y, data=diamonds, main="Diamonds",
   xlab="Width", ylab="Price")

boxplot(price ~ z, data=diamonds, main="Diamonds",
   xlab="Depth", ylab="Price")

boxplot(price ~ depth, data=diamonds, main="Diamonds",
   xlab="Total Depth %", ylab="Price")

boxplot(price ~ table, data=diamonds, main="Diamonds",
   xlab="Table", ylab="Price")
```

```{r integer encoding for cut, include = FALSE}
#Cut
factors <- factor(diamonds$cut)
as.numeric (factors)

cut_category <- c("Fair", "Good", "Very Good", "Premium", "Ideal")
cut_ordered <- factor(diamonds$cut, levels=cut_category)
diamonds$cut_in_num_order <- c(as.numeric(cut_ordered))

#Color
factors <- factor(diamonds$color)
as.numeric (factors)

color_category <- c("D", "E", "F", "G", "H", "I", "J")
color_ordered <- factor(diamonds$color, levels=color_category)
diamonds$color_in_num_order <- c(as.numeric(color_ordered))

#Clarity 
factors <- factor(diamonds$clarity)
as.numeric (factors)

clarity_category <- c("IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1")
clarity_ordered <- factor(diamonds$clarity, levels=clarity_category)
diamonds$clarity_in_num_order <- c(as.numeric(clarity_ordered))
```

```{r rename and create columns}
colnames(diamonds)[colnames(diamonds) == 'depth'] <- 'depth_in_percent'
colnames(diamonds)[colnames(diamonds) == 'table'] <- 'table_in_percent'
colnames(diamonds)[colnames(diamonds) == 'x'] <- 'length_in_mm'
colnames(diamonds)[colnames(diamonds) == 'y'] <- 'width_in_mm'
colnames(diamonds)[colnames(diamonds) == 'z'] <- 'depth_in_mm'
diamonds <- within(diamonds, volume <- width_in_mm * length_in_mm * depth_in_mm)
```

```{r drop rows with 0 in x, y, z, depth, table, volume}
diamonds <- subset(diamonds, length_in_mm != 0 )
diamonds <- subset(diamonds, width_in_mm != 0 )
diamonds <- subset(diamonds, depth_in_mm != 0 )
diamonds <- subset(diamonds, depth_in_percent != 0 )
diamonds <- subset(diamonds, table_in_percent != 0 )
diamonds <- subset(diamonds, volume != 0 )
dim(diamonds)
```

```{r checking data, message = FALSE}
summary(diamonds$volume)
summary(diamonds$price)
summary(diamonds$carat)
hist(diamonds$price)
hist(diamonds$carat)
hist(diamonds$volume)
```

```{r log diamonds, message = FALSE, include=FALSE}
diamonds[,c('depth_in_percent','depth_in_mm','carat','price','width_in_mm','length_in_mm','table_in_percent','volume')] <- log(diamonds[,c('depth_in_percent','depth_in_mm','carat','price','width_in_mm','length_in_mm','table_in_percent','volume')])
head(diamonds)
```

```{r plot carat distribution, echo=FALSE, results='hide'}
carat_dist = dnorm(diamonds$carat, mean(diamonds$carat), sd(diamonds$carat))
plot(diamonds$carat,carat_dist)

depth_in_percent_dist = dnorm(diamonds$depth_in_percent, mean(diamonds$depth_in_percent), sd(diamonds$depth_in_percent))
plot(diamonds$depth_in_percent,depth_in_percent_dist)

table_in_percent_dist = dnorm(diamonds$table_in_percent, mean(diamonds$table_in_percent), sd(diamonds$table_in_percent))
plot(diamonds$table_in_percent,table_in_percent_dist)
```

``` {r Large Sample Assumptions}

# Looking at the distribution of Variance of the different features
hist(diamonds$price)
hist(diamonds$carat)
hist(diamonds$volume)
```

```{r create correlation table}
data <- cor(diamonds[sapply(diamonds, is.numeric)])
data
```

```{r create heatmap}
data <- cor(diamonds[sapply(diamonds, is.numeric)])
data1 <- melt(data)
ggplot(data1, aes(x = Var1, y = Var2, fill = value)) +
                  geom_tile() + 
                  theme(axis.text.x = element_text(angle = 45, hjust = 1))
                  #geom_text(aes(label = value)) +
                  #scale_fill_gradient(low = "white", high = "#1b98e0") +
                  

```

```{r create scatter plots}
#Price based on Carat

ggplot(diamonds, aes(carat, price)) +
        geom_point() + 
        ggtitle("Price based on Carat") +
        geom_smooth(method = "lm")

#Price based on Depth
ggplot(diamonds, aes(x = depth_in_percent, y = price)) +
        geom_point() + 
        ggtitle("Price based on Depth") +
        geom_smooth(method = "lm")

#Price based on table_in_percent
ggplot(diamonds, aes(x = table_in_percent, y = price)) +
        geom_point() + 
        ggtitle("Price based on Table") +
        geom_smooth(method = "lm")

#create scatter plot price based carat
ggplot(diamonds, aes(x=carat, y=price, color=clarity)) +
        geom_point(alpha=0.5, size=5) + 
        ggtitle("Price based on Carat and Clarity") +
        geom_smooth(method = "lm", color="black") +
        labs(color="clarity") +
        scale_fill_discrete(breaks=c("IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1"))

```

``` {r linear model 1 diamonds}
mod1ex = lm(formula = (price ~ carat), data = diamonds)
summary(mod1ex)

hist(carat_dist, main= "Carat Distribution")
hist(diamonds$price, main= "Price Distribution")
#skewness for carat
skewness(diamonds$carat)
#skewness for price
skewness(diamonds$price)
#The dataset could be clustered if the diamonds was made in the same location.

ggplot(diamonds, aes(carat, price, color=cut)) +
        geom_point() + 
        ggtitle("Price based on Carat")

#LCE
ggplot(mod1ex,aes(x = predict(mod1ex), y = resid(mod1ex))) +
  geom_point() + 
  ggtitle('Residuals vs Fitted') + 
  stat_smooth()

ggplot(diamonds,aes(x = price, y = resid(mod1ex))) +
  geom_point() + 
  ggtitle('Price vs Fitted') + 
  stat_smooth()

# Homoskedaciy
plot(mod1ex, which = 3)
bptest(diamonds$price ~ diamonds$carat)

#Distribution of errors
hist(mod1ex$residuals)
plot(mod1ex, which = 2)
```

``` {r linear model 2 diamonds}
mod2ex = lm(formula = (price ~ carat + color_in_num_order + clarity_in_num_order), data = diamonds)
summary(mod2ex)

hist(carat_dist, main= "Carat Distribution")
hist(diamonds$price, main= "Price Distribution")

#skewness for carat
skewness(diamonds$carat)
#skewness for price
skewness(diamonds$price)
#skewness for Clarity
skewness(diamonds$clarity_in_num_order)
#skewness for Color
skewness(diamonds$color_in_num_order)

#The dataset could be clustered if the diamonds was made in the same location.
ggplot(diamonds, aes(carat, price, color=cut)) +
        geom_point() + 
        ggtitle("Price vs Carat")
ggplot(diamonds, aes(color_in_num_order, price)) +
        geom_point() + 
        ggtitle("Price vs Color")
ggplot(diamonds, aes(clarity_in_num_order, price)) +
        geom_point() + 
        ggtitle("Price vs Clarity")

coeftest(mod2ex, vcovHC(mod2ex))
vcovHC(mod2ex)
ols_vif_tol(mod2ex)

#LCE
ggplot(mod2ex,aes(x = predict(mod2ex), y = resid(mod2ex))) +
  geom_point() + 
  ggtitle('Residuals vs Fitted') + 
  stat_smooth()

ggplot(diamonds,aes(x = price, y = resid(mod2ex))) +
  geom_point() + 
  ggtitle('Price vs Fitted') + 
  stat_smooth()

# Homoskedaciy
plot(mod2ex, which = 3)
bptest(mod2ex)

#Distribution of errors
hist(mod2ex$residuals)
plot(mod2ex, which = 2)

#anova
anova(mod2ex,mod1ex,test = "F")

```

``` {r linear model 3 diamonds}
mod3ex = lm(formula = (price ~ carat + color_in_num_order + clarity_in_num_order + volume), data = diamonds)
summary(mod3ex)

hist(carat_dist, main= "Carat Distribution")
hist(diamonds$price, main= "Price Distribution")
hist(diamonds$depth_in_percent, main= "Depth")
hist(diamonds$volume, main= "Volume")
hist(diamonds$table_in_percent, main= "Table")
#skewness for carat
skewness(diamonds$carat)
#skewness for price
skewness(diamonds$price)
#skewness for Volume
skewness(diamonds$volume)
#skewness for Clarity
skewness(diamonds$clarity)
#skewness for Color
skewness(diamonds$color)


#The dataset could be clustered if the diamonds was made in the same location.
ggplot(diamonds, aes(carat, price, color=cut)) +
        geom_point() + 
        ggtitle("Price vs Carat")
ggplot(diamonds, aes(color, price)) +
        geom_point() + 
        ggtitle("Price vs Color")
ggplot(diamonds, aes(clarity, price)) +
        geom_point() + 
        ggtitle("Price vs Clarity")
ggplot(diamonds, aes(volume, price)) +
        geom_point() + 
        ggtitle("Price vs Volume")

coeftest(mod3ex, vcovHC(mod3ex))
ols_vif_tol(mod3ex)

#LCE
ggplot(mod3ex,aes(x = predict(mod3ex), y = resid(mod3ex))) +
  geom_point() + 
  ggtitle('Residuals vs Fitted') + 
  stat_smooth()

ggplot(diamonds,aes(x = price, y = resid(mod3ex))) +
  geom_point() + 
  ggtitle('Price vs Fitted') + 
  stat_smooth()

ggplot(diamonds,aes(x = volume, y = resid(mod3ex))) +
  geom_point() + 
  ggtitle('Volume vs Fitted') + 
  stat_smooth()

# Homoskedaciy
plot(mod3ex, which = 3)
bptest(mod3ex)

#Distribution of errors
hist(mod3ex$residuals)
plot(mod3ex, which = 2)

anova(mod3ex,mod2ex,test = "F")
anova(mod3ex,mod1ex,test = "F")
```

```{r display regression table, message=FALSE, echo=FALSE, results='asis'}
stargazer(mod1ex, mod2ex, mod3ex, 
          #type = "latex",
          type = "text",
          style = "default", 
          out = "models.txt", 
          #column.labels = c("Mod1ex", "Mod2ex", "Mod3ex"), 
          column.labels = NULL,
          column.separate = NULL,
          intercept.bottom = FALSE,
          header = FALSE,
          digits = 2,
          title = "Table 1: Estimated Regressions",
          dep.var.caption  = "Output Variable: price per carat",
          dep.var.labels   = c("","",""),
          star.cutoffs = c(0.05, 0.01, 0.001),
          covariate.labels = c("Constant", "Carat", "Color", "Clarity", "Volume (Length * Width * Depth)"),
          align = TRUE,
          no.space=TRUE,
          omit.stat = "f",
          notes = "\\parbox[t]{7cm}{$HC_1$ robust standard errors in parentheses.}" 
          )

```

``` {r data cleaning for confirmation_set}
confirmation_set %>% drop_na()
confirmation_set <- subset(confirmation_set, select=c(carat, cut, color, clarity, depth, table, price, x, y, z))
#Cut
factors <- factor(confirmation_set$cut)
as.numeric (factors)
cut_category <- c("Fair", "Good", "Very Good", "Premium", "Ideal")
cut_ordered <- factor(confirmation_set$cut, levels=cut_category)
confirmation_set$cut_in_num_order <- c(as.numeric(cut_ordered))
#Color
factors <- factor(confirmation_set$color)
as.numeric (factors)
color_category <- c("D", "E", "F", "G", "H", "I", "J")
color_ordered <- factor(confirmation_set$color, levels=color_category)
confirmation_set$color_in_num_order <- c(as.numeric(color_ordered))
#Clarity 
factors <- factor(confirmation_set$clarity)
as.numeric (factors)
clarity_category <- c("IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1")
clarity_ordered <- factor(confirmation_set$clarity, levels=clarity_category)
confirmation_set$clarity_in_num_order <- c(as.numeric(clarity_ordered))
colnames(confirmation_set)[colnames(confirmation_set) == 'depth'] <- 'depth_in_percent'
colnames(confirmation_set)[colnames(confirmation_set) == 'table'] <- 'table_in_percent'
colnames(confirmation_set)[colnames(confirmation_set) == 'x'] <- 'length_in_mm'
colnames(confirmation_set)[colnames(confirmation_set) == 'y'] <- 'width_in_mm'
colnames(confirmation_set)[colnames(confirmation_set) == 'z'] <- 'depth_in_mm'
confirmation_set <- within(confirmation_set, volume <- width_in_mm * length_in_mm * depth_in_mm)
confirmation_set[,c('depth_in_percent','depth_in_mm','carat','price','width_in_mm','length_in_mm','table_in_percent','volume')] <- log(confirmation_set[,c('depth_in_percent','depth_in_mm','carat','price','width_in_mm','length_in_mm','table_in_percent','volume')])
#sum(is.infinite(confirmation_set$volume))
confirmation_set$volume[is.infinite(confirmation_set$volume)] <- NA
confirmation_set <- na.omit(confirmation_set)
#sum(is.na(confirmation_set$volume))
```

``` {r linear model 1}
mod1 = lm(formula = (price ~ carat), data = confirmation_set)
summary(mod1)

hist(carat_dist, main= "Carat Distribution")
hist(confirmation_set$price, main= "Price Distribution")
#skewness for carat
skewness(confirmation_set$carat)
#skewness for price
skewness(confirmation_set$price)
#The dataset could be clustered if the diamonds was made in the same location.

ggplot(confirmation_set, aes(carat, price, color=cut)) +
        geom_point() + 
        ggtitle("Price based on Carat")

```
``` {r linear model 2}
mod2 = lm(formula = (price ~ carat + color_in_num_order + clarity_in_num_order), data = confirmation_set)
summary(mod2)

hist(carat_dist, main= "Carat Distribution")
hist(confirmation_set$price, main= "Price Distribution")

#skewness for carat
skewness(confirmation_set$carat)
#skewness for price
skewness(confirmation_set$price)
#skewness for Clarity
skewness(confirmation_set$clarity_in_num_order)
#skewness for Color
skewness(confirmation_set$color_in_num_order)

#The dataset could be clustered if the diamonds was made in the same location.
ggplot(confirmation_set, aes(carat, price, color=cut)) +
        geom_point() + 
        ggtitle("Price vs Carat")
ggplot(confirmation_set, aes(color_in_num_order, price)) +
        geom_point() + 
        ggtitle("Price vs Color")
ggplot(confirmation_set, aes(clarity_in_num_order, price)) +
        geom_point() + 
        ggtitle("Price vs Clarity")

coeftest(mod2, vcovHC(mod2))
vcovHC(mod2)
ols_vif_tol(mod2)
anova(mod2,mod2,test = "F")
anova(mod2,mod1,test = "F")
```

``` {r linear model 3}
mod3 = lm(formula = (price ~ carat + color_in_num_order + clarity_in_num_order + volume), data = confirmation_set)
summary(mod3)

hist(carat_dist, main= "Carat Distribution")
hist(confirmation_set$price, main= "Price Distribution")

#skewness for carat
skewness(confirmation_set$carat)
#skewness for price
skewness(confirmation_set$price)
#skewness for volume
skewness(confirmation_set$volume)
#skewness for Clarity
skewness(confirmation_set$clarity_in_num_order)
#skewness for Color
skewness(confirmation_set$color_in_num_order)

#The dataset could be clustered if the diamonds was made in the same location.
ggplot(confirmation_set, aes(carat, price, color=cut)) +
        geom_point() + 
        ggtitle("Price vs Carat")
ggplot(confirmation_set, aes(color_in_num_order, price)) +
        geom_point() + 
        ggtitle("Price vs Color")
ggplot(confirmation_set, aes(clarity_in_num_order, price)) +
        geom_point() + 
        ggtitle("Price vs Clarity")
ggplot(confirmation_set, aes(volume, price)) +
        geom_point() + 
        ggtitle("Price vs Volume")

coeftest(mod3, vcovHC(mod3))
vcovHC(mod3)
ols_vif_tol(mod3)
anova(mod3,mod2,test = "F")
anova(mod3,mod1,test = "F")
```


```{r display regression table, message=FALSE, echo=FALSE, results='asis'}
stargazer(mod1, mod2, mod3, 
          #type = "latex",
          type = "text",
          style = "default", 
          out = "models.txt", 
          #column.labels = c("Mod1", "Mod2", "Mod3"), 
          column.labels = NULL,
          column.separate = NULL,
          intercept.bottom = FALSE,
          header = FALSE,
          digits = 2,
          title = "Table 1: Estimated Regressions",
          dep.var.caption  = "Output Variable: price per carat",
          dep.var.labels   = c("","",""),
          star.cutoffs = c(0.05, 0.01, 0.001),
          covariate.labels = c("Constant", "Carat", "Color", "Clarity", "Volume (Length * Width * Depth)"),
          align = TRUE,
          no.space=TRUE,
          omit.stat = "f",
          notes = "\\parbox[t]{7cm}{$HC_1$ robust standard errors in parentheses.}" 
          )

```


